#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [15]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [16]:
def isSymmetric(a):
    counter = 0
    if(a.shape[0]!=a.shape[1]):
        return False
    for i in range(a.shape[0]):
        for j in range(a.shape[0]):
            if(a[i][j]!=a[j][i]):
                counter = counter + 1
    if(counter == 0):
        return True
    if(counter>0):
        return False
   
    
    
    
    
    
    
    

In [6]:
isSymmetric(np.array([[6,9],[9,6]]))

True

Test your function on the two matrices below

In [7]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [8]:
print(A)
isSymmetric(A)

[[0.19986374 0.96525955 0.13981505 0.04511905 0.86726541]
 [0.43800419 0.55851364 0.85550063 0.06167998 0.00236755]
 [0.14140299 0.72218006 0.69468611 0.94653746 0.09540979]
 [0.35058547 0.25821095 0.38042205 0.17746331 0.01536633]
 [0.33565424 0.5911206  0.77964087 0.09955154 0.52058241]]


False

In [9]:
print(SymMatrix)
isSymmetric(SymMatrix)


[[0.19986374 0.70163187 0.14060902 0.19785226 0.60145983]
 [0.70163187 0.55851364 0.78884034 0.15994546 0.29674407]
 [0.14060902 0.78884034 0.69468611 0.66347975 0.43752533]
 [0.19785226 0.15994546 0.66347975 0.17746331 0.05745894]
 [0.60145983 0.29674407 0.43752533 0.05745894 0.52058241]]


True

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [10]:
def transposo(a):

    b = np.zeros((a.shape[0],a.shape[1]))


    i = 0

    while(i<a.shape[0]):
        b[i,:] = a[:,i]
        i+=1


    return b

In [11]:
transposo(np.array([[1,2],[3,4]]))

array([[1., 3.],
       [2., 4.]])

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [12]:
A = np.random.rand(6,6);
A_T=transposo(A)

print(A_T-A)
#This would've been a zero matrix if A_T and A were equal.

ATT = transposo(A_T)
print(ATT-A)





[[ 0.          0.39475902 -0.29176315 -0.62663734 -0.0957583  -0.82670201]
 [-0.39475902  0.         -0.60841648  0.54987857 -0.43500614 -0.06662089]
 [ 0.29176315  0.60841648  0.         -0.33642274 -0.08913223 -0.1260835 ]
 [ 0.62663734 -0.54987857  0.33642274  0.         -0.41334866 -0.24600065]
 [ 0.0957583   0.43500614  0.08913223  0.41334866  0.          0.17270938]
 [ 0.82670201  0.06662089  0.1260835   0.24600065 -0.17270938  0.        ]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [15]:
def maxo(a):
    i = 0
    m = 0
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if (a[i][j]>m):
                m=a[i][j]
    print(m)
    

Check your result by comparing to `np.max(A)` for the below random matrix

In [16]:
A = np.random.rand(4,5)
print(A)
print(A.shape)
maxo(A)



[[0.13465994 0.73558713 0.32533659 0.90039452 0.44442943]
 [0.14420713 0.16352491 0.422469   0.95046011 0.20147479]
 [0.84484085 0.66250157 0.65842997 0.35142706 0.65721712]
 [0.92728116 0.83286013 0.49035576 0.67396249 0.48800598]]
(4, 5)
0.9504601081557533


Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [5]:
def normy(a):
    
    m = 0
    s = 0
    j = 0
    while j < a.shape[1]:
        for i in range(a.shape[0]):
            s = s + np.abs(a[i][j])
        
        if(s>m):
            m = s
        s = 0
        j = j + 1
        
    print("L1 norm = "+str(m))
            
       
        
            
            
        

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [65]:
A = np.random.rand(3,4)
print(A)
normy(A)

[[0.32341527 0.28533887 0.10393664 0.73343993]
 [0.95798185 0.70103748 0.61026277 0.26476121]
 [0.50220114 0.69164479 0.05602602 0.25131294]]
L1 norm = 1.7835982525569773


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [70]:
def normyTwo(a):
    
    m = 0
    s = 0
    j = 0
    while j < a.shape[0]:
        for i in range(a.shape[1]):
            s = s + np.abs(a[j][i])
        
        if(s>m):
            m = s
        s = 0
        j = j + 1
        
    print("L infinity norm = "+str(m))

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [71]:
A = np.random.rand(3,4)
print(A)
normyTwo(A)


[[0.40313341 0.66402404 0.15055621 0.36426948]
 [0.50383303 0.78550881 0.95189842 0.1922437 ]
 [0.93975323 0.82718347 0.34386545 0.28213317]]
L infinity norm = 2.433483960578659


Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [9]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [81]:
np.linalg.cond(A3)


# A1 is ill-conditioned because A1's condition number is extremely large.
# cond(A1) = 13334936994.070848
# cond(A2) = 21.55
# cond(A3) = 15.12

15.12244969941062

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

In [29]:
b = np.array([1,2,3,4])
db = np.array([0.1,0,0,0])

x1 = np.dot(la.inv(A1),b)
dx1 = np.dot(la.inv(A1),db)

x2 = np.dot(la.inv(A2),b)
dx2 = np.dot(la.inv(A2),db)

changex1 = 100*(la.norm(dx1,2)/la.norm(x1,2))
changex2 = 100*(la.norm(dx2,2)/la.norm(x2,2))
smallchangeb = 100*(la.norm(db,2)/la.norm(b,2))

print(x1+dx1)
print(np.dot(la.inv(A1),b+db))

print(changex1)
print(changex2)
print(smallchangeb)

[-4.56447442e+08 -2.28223724e+08  2.28223725e+08  2.28223722e+08]
[-4.56447442e+08 -2.28223724e+08  2.28223725e+08  2.28223722e+08]
512.6206098890643
10.483582220339125
1.8257418583505536


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [8]:
# Answer here
# A1 : 512.62%  A2: 10.48%
# A1 is more sensitive to small changes in b, because the percentage change in x due to a small change in b is far greater 
# than A2. x in A1 rose by 512.62%, compared to A2's rise in x of just 10.48%

Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [7]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [40]:
A  = np.array([[1,4,5],[4,5,4],[6,7,9]])
w, v = la.eig(A)


wsorted = np.array([15.78569318, 1.26595327, -2.05164645])
print("Eigenvalues sorted by descending value:  ",wsorted)

print("The print statements below show that each eigenvalue/eigenvector pair satisfies Ax = lamba(x)")
print(np.dot(A,v[:,0])," = ", np.dot(w[0],v[:,0]) )
print(np.dot(A,v[:,1])," = ", np.dot(w[1],v[:,1]) )
print(np.dot(A,v[:,2])," = ", np.dot(w[2],v[:,2]) )








Eigenvalues sorted by descending value:   [15.78569318  1.26595327 -2.05164645]
The print statements below show that each eigenvalue/eigenvector pair satisfies Ax = lamba(x)
[ -6.1962015   -7.01266016 -12.71289871]  =  [ -6.1962015   -7.01266016 -12.71289871]
[ 1.83806756 -0.74382849 -0.52676368]  =  [ 1.83806756 -0.74382849 -0.52676368]
[ 0.12430099 -0.98053324  0.79103825]  =  [ 0.12430099 -0.98053324  0.79103825]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [104]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

In [145]:

print(Eigs[0])
print (v)

[5.17297120e+00 1.52979716e-03 1.98622783e-01 4.81669270e-01]
[[ 0.71538265  0.68301529  0.14168212 -0.04054567]
 [ 0.43087578 -0.34802856 -0.64758011 -0.52331842]
 [ 0.40381884 -0.328043   -0.22152224  0.82477029]
 [ 0.37350243 -0.55204531  0.71518814 -0.21035171]]


In [106]:
#POWER METHOD
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    
    # Create a random initial vector
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        Ax      = np.dot(A,x)
        lamprev = lam
        lam = la.norm(Ax,2)/la.norm(x,2)
        x = Ax
        
    x = x/la.norm(x)
    return (lam,x)

In [141]:
maxeig = MaxEigenvalue(A,1e-14)[0]
print("Largest eigenvalue = ",maxeig)



Largest eigenvalue =  5.172971199844757


In [113]:
#POWER METHOD TO THE INVERSE OF A 

MinEigenvalue = 1/MaxEigenvalue(la.inv(A),1e-14)[0]
print("Smallest eigenvalue = ",MinEigenvalue)

Smallest eigenvalue =  0.0015297971635957477


In [146]:
#HOTELLING'S DEFLATION TWICE
B = A - MaxEigenvalue(A,1e-14)[0]*np.outer(MaxEigenvalue(A,1e-14)[1],MaxEigenvalue(A,1e-14)[1])
second = MaxEigenvalue(B, 1e-12)
secondval = second[0]
print("Second largest eigenvalue = ",secondval)

C = B - MaxEigenvalue(B,1e-14)[0]*np.outer(MaxEigenvalue(B,1e-14)[1],MaxEigenvalue(B,1e-14)[1])
third = MaxEigenvalue(C, 1e-12)
thirdval = third[0]
print("Third largest eigenvalue = ",thirdval)


Second largest eigenvalue =  0.4816692703106321
Third largest eigenvalue =  0.19862278268099304


Check your answers against Numpy's results from `la.eig(A)`

In [139]:
print(la.eig(A)[0])

[5.17297120e+00 1.52979716e-03 1.98622783e-01 4.81669270e-01]


In [144]:
print(maxeig,MinEigenvalue, thirdval, secondval)

5.172971199844757 0.0015297971635957477 0.1986227826809928 0.48166927031063367


Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.